# Generated by Django 3.2.6 on 2021-08-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_areas', models.CharField(default=None, max_length=50)),
                ('crowdy_places', models.CharField(default=None, max_length=50)),
                ('international_travel', models.CharField(default=None, max_length=250)),
                ('victim_contact', models.CharField(default=None, max_length=250)),
            ],
            options={
                'db_table': 'travel',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(default=None, max_length=50)),
                ('age', models.CharField(default=None, max_length=50)),
                ('diseases', models.TextField(default=None, max_length=250)),
                ('medication', models.CharField(default=None, max_length=250)),
                ('transplant', models.CharField(default=None, max_length=250)),
                ('vaccination', models.CharField(default=None, max_length=250)),
                ('user', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health',
            },
        ),
    ]
