# Generated by Django 3.2.6 on 2021-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Female', max_length=50)),
                ('age', models.CharField(choices=[('18-25', '18-25'), ('36-54', '36-54'), ('55-74', '55-74'), ('75 and above', '75 and above')], default='0', max_length=50)),
                ('disease', models.CharField(default='TB', max_length=250)),
                ('medication', models.CharField(default='Yes', max_length=250)),
                ('transplant', models.CharField(default='No', max_length=250)),
                ('vaccination', models.CharField(default='Yes', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelqn1', models.CharField(default='Question 1', max_length=150)),
            ],
        ),
    ]
