# Generated by Django 3.1 on 2021-03-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.TextField(max_length=250)),
                ('choice2', models.TextField(max_length=250)),
                ('choice3', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthqn1', models.CharField(max_length=50)),
                ('healthqn2', models.CharField(max_length=50)),
                ('healthqn3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelqn1', models.CharField(max_length=50)),
                ('travelqn2', models.CharField(max_length=50)),
                ('travelqn3', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='datamap',
            name='filtered',
            field=models.CharField(default='Filter results', help_text='Filter data', max_length=50),
        ),
    ]
