# Generated by Django 3.2.6 on 2021-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='travelqn1',
        ),
        migrations.AlterField(
            model_name='health',
            name='disease',
            field=models.CharField(choices=[('TB', 'TB'), ('Asthma', 'Asthma'), ('Blood Disorder', 'Blood Disorder'), ('Cancer', 'Cancer'), ('Heart Disease', 'Heart Disease'), ('Diabetes', 'Diabetes'), ('Obesity', 'Obesity')], default='TB', max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='health',
            name='medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='transplant',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='vaccination',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250),
        ),
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='health',
            table='health',
        ),
        migrations.AlterModelTable(
            name='travel',
            table='travel',
        ),
    ]
