# Generated by Django 3.1.7 on 2021-04-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20210322_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered', models.CharField(default='Filter results', help_text='Filter data', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tabular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Result',
        ),
        migrations.RemoveField(
            model_name='datamap',
            name='filtered',
        ),
    ]
