# Generated by Django 3.2.6 on 2021-08-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20210812_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='covidvictim_contact',
            field=models.CharField(default='No', max_length=250),
        ),
        migrations.AddField(
            model_name='travel',
            name='crowdy_places',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='travel',
            name='international_travel',
            field=models.CharField(default='Yes', max_length=250),
        ),
        migrations.AddField(
            model_name='travel',
            name='risk_areas',
            field=models.CharField(default='Yes', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.CharField(default='18-25', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='disease',
            field=models.CharField(default='Asthma', max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(default='Female', max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='medication',
            field=models.CharField(default='Yes', max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='transplant',
            field=models.CharField(default='No', max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='vaccination',
            field=models.CharField(default='Yes', max_length=250),
        ),
    ]
