# Generated by Django 3.2 on 2021-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20210407_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Tabular',
        ),
        migrations.RemoveField(
            model_name='datafilter',
            name='filtered',
        ),
        migrations.AddField(
            model_name='health',
            name='healthqn4',
            field=models.CharField(default='Question 4', max_length=150),
        ),
        migrations.AddField(
            model_name='travel',
            name='travelqn4',
            field=models.CharField(default='Question 4', max_length=150),
        ),
        migrations.AlterField(
            model_name='health',
            name='healthqn1',
            field=models.CharField(default='Question 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='health',
            name='healthqn2',
            field=models.CharField(default='Question 2', max_length=150),
        ),
        migrations.AlterField(
            model_name='health',
            name='healthqn3',
            field=models.CharField(default='Question 3', max_length=150),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelqn1',
            field=models.CharField(default='Question 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelqn2',
            field=models.CharField(default='Question 2', max_length=150),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelqn3',
            field=models.CharField(default='Question 3', max_length=150),
        ),
    ]
