# Generated by Django 3.2.6 on 2021-08-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20210816_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='disease',
            new_name='diseases',
        ),
    ]
