# Generated by Django 3.2.6 on 2021-08-25 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0003_travel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='user',
        ),
        migrations.AddField(
            model_name='health',
            name='active_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travel',
            name='active_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
