# Generated by Django 3.2.6 on 2021-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_rename_disease_health_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='covidvictim_contact',
        ),
        migrations.AddField(
            model_name='travel',
            name='victim_contact',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='diseases',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='health',
            name='medication',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='transplant',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='health',
            name='vaccination',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='travel',
            name='crowdy_places',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='international_travel',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='travel',
            name='risk_areas',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
