# Generated by Django 3.2.6 on 2021-08-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_auto_20210413_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFilter',
        ),
    ]
