# Generated by Django 3.2.6 on 2021-08-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_auto_20210825_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='user_id',
            new_name='user',
        ),
    ]
